config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  namespace :public do
    resources :socials
  end
  devise_for :admins, controllers: {
       sessions:      'admins/sessions',
       passwords:     'admins/passwords',
       registrations: 'admins/registrations'
     }
 devise_for :users, controllers: {
       sessions:      'users/sessions',
       passwords:     'users/passwords',
       registrations: 'users/registrations'
     }
  resources :users
 
     get '/admin' => 'admins/homes#top'
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   # get '/admin' => 'admin/homes#top'
     root 'public/homes#top'
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :socials
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @user_new = User.new
    # @user_social_snstypes = @user.social.snstypes
    # @user_social_urls = @user.social.urls
  end
  def update
    @user = User.find(params[:id]).update(user_params)
    redirect_to root_path
  end
  def index
    @user = current_user
    @users = User.all
  end
  
  private
  def user_params
    params.require(:user).permit(:introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container user">
    <div class="row users-area no-gutters">
      <h2 style="font-size:24px;">ユーザー一覧</h2>
      <div class="row users-header no-gutters">
        <div class="col-xs-7">【name】</div>
        <!--<div class="col-xs-">【introduction】</div>-->
        <div class="col-xs-5">【sns】</div>
      </div>
      <% a = 0 %>
      <% @users.each do |user| %>
      <div class="row no-gutters user-inners">
        <div class="col-xs-7  text-left">
          【<%= a += 1 %>】<%= link_to user.name, user_path(user.id) %>
        </div>
        <!--<div class="col-xs-5">-->
           <%# user.introduction.truncate(20)  %>
        <!--</div>-->
        <div class="col-xs-5">
           <% user.socials.each do |social| %>
              <% if social.snstype["twitter"].present? %>
                <%= link_to social.url do %>
                  <i class="fab fa-twitter-square"></i>
                <% end %>
              <% end %>
              <% if social.snstype["blog"].present? %>
                <%= link_to social.url do %>
                  <i class="fab fa-youtube"></i>
                <% end %>
              <% end %>
              <% if social.snstype["instagram"].present? %>
                <%= link_to social.url do %>
                  <i class="fab fa-instagram-square"></i>
                <% end %>
              <% end %>
              <% if social.snstype["line"].present? %>
                <%= link_to social.url do %>
                  <i class="fab fa-line"></i>
                <% end %>
              <% end %>
              <% if social.snstype["facebook"].present? %>
                <%= link_to social.url do %>
                  <i class="fab fa-facebook"></i>
                <% end %>
              <% end %>
            <% end %>
            <br>
            <% if current_user.id == user.id %>
              <%= link_to 'SNS追加', new_public_social_path %>
            <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <!--<div class="iconarea row">-->
    <!--  <i class="fab fa-youtube"></i>-->
    <!--  <i class="fab fa-tiktok text-right"></i>-->
    <!--  <i class="fab fa-instagram-square text-right"></i>-->
    <!--  <i class="fab fa-facebook text-right"></i>-->
    <!--  <i class="fab fa-line text-right"></i>-->
    <!--  <i class="fab fa-twitter-square text-right"></i>-->
    <!--</div>-->
</div>

app/views/users/show.html.erb
<div class="container user">
    <div class="user row">
        <%= @user.name %>さんのページ
        <div class="box1">
          <div class="box2">
          <% @user.socials.each do |social| %>
            <% if social.snstype["twitter"].present? %>
              <%= image_tag 'img/twitter.png'%>
            <% end %>
            <% if social.snstype["blog"].present? %>
              <%= image_tag 'img/blog.png' %>
            <% end %>
            <% if social.snstype["instagram"].present? %>
              <%= image_tag 'img/insta.png' %>
            <% end %>
            <% if social.snstype["line"].present? %>
              <%= image_tag 'img/line.png' %>
            <% end %>
            <% if social.snstype["facebook"].present? %>
              <%= image_tag 'img/fb.png' %>
            <% end %>
          <% end %>
          </div>
        </div>
        <div class="box3">
        <%= form_with model: @user, local: true do |f| %>
          <%= f.label :introduction %>
          <%= f.text_area :introduction %>
          <%= f.submit %>
        <% end %>
         <%= @user.introduction %>
        </div>
    </div>
    <div class="iconarea text-center">
      <p>【登録可能なSNS】</p>
      <i class="fab fa-youtube"></i>
      <i class="fab fa-tiktok"></i>
      <i class="fab fa-instagram-square"></i>
      <i class="fab fa-facebook"></i>
      <i class="fab fa-line"></i>
      <i class="fab fa-twitter-square"></i>
      <%= link_to 'SNS追加', new_public_social_path %>
    </div>
    
    
</div>